# Generated by Django 4.2.7 on 2023-11-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='vid',
            new_name='id',
        ),
    ]
