# Generated by Django 4.2.7 on 2023-12-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_rename_vid_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, default='OIP.jpeg', upload_to='thumbnails/'),
        ),
    ]
